[package]
name = "http-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2"
clap = { version = "4.0", features = ["derive"] }
http = "0.2"
http-body = { version = "0.4" }
hyper = { version = "0.14", features = [ "full"] }
tokio = { version = "1.21", features = ["full"] }
